#!/bin/bash
SHOULD_BUILD=1
for var in "$@"
do
  if [[ "$var" == "--skip-build" ]]; then
    SHOULD_BUILD=0
  fi
done

if [[ SHOULD_BUILD -eq 1 ]]; then
   rm -rf ./build/bin
   echo "Building all platforms: wails build --upx"
   wails build --upx --nsis --platform=linux,windows
fi

echo "Creating .deb file for linux platforms."
CURRENT_DIR="$PWD"

if [ -d "$CURRENT_DIR/build/linux" ]; then
  (cd "$CURRENT_DIR/build/linux" && nfpm pkg --packager deb --target ../bin/)
else
  echo "You are not in the right directory. Head back to the root directory where `build-all-platforms` is located."
fi