// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Authenticate(arg1) {
  return window['go']['kuddle']['App']['Authenticate'](arg1);
}

export function CleanUp() {
  return window['go']['kuddle']['App']['CleanUp']();
}

export function CreateSession(arg1, arg2) {
  return window['go']['kuddle']['App']['CreateSession'](arg1, arg2);
}

export function DeleteSession(arg1) {
  return window['go']['kuddle']['App']['DeleteSession'](arg1);
}

export function Download(arg1) {
  return window['go']['kuddle']['App']['Download'](arg1);
}

export function DownloadBase64(arg1) {
  return window['go']['kuddle']['App']['DownloadBase64'](arg1);
}

export function EditSession(arg1, arg2, arg3) {
  return window['go']['kuddle']['App']['EditSession'](arg1, arg2, arg3);
}

export function GetSession(arg1) {
  return window['go']['kuddle']['App']['GetSession'](arg1);
}

export function HasRegistered() {
  return window['go']['kuddle']['App']['HasRegistered']();
}

export function LocateSessions(arg1) {
  return window['go']['kuddle']['App']['LocateSessions'](arg1);
}

export function Register(arg1) {
  return window['go']['kuddle']['App']['Register'](arg1);
}

export function RequestScreenshot() {
  return window['go']['kuddle']['App']['RequestScreenshot']();
}

export function Test(arg1) {
  return window['go']['kuddle']['App']['Test'](arg1);
}

export function Upload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['kuddle']['App']['Upload'](arg1, arg2, arg3, arg4, arg5);
}
