// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {kuddle} from '../models';

export function Authenticate(arg1:string):Promise<boolean>;

export function CleanUp():Promise<void>;

export function CreateSession(arg1:string,arg2:kuddle.Session):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function Download(arg1:string):Promise<kuddle.ImageDownloadResult>;

export function DownloadBase64(arg1:string):Promise<string>;

export function EditSession(arg1:string,arg2:string,arg3:kuddle.Session):Promise<void>;

export function GetSession(arg1:string):Promise<kuddle.Session>;

export function HasRegistered():Promise<boolean>;

export function LocateSessions(arg1:string):Promise<Array<string>>;

export function Register(arg1:string):Promise<void>;

export function RequestScreenshot():Promise<string>;

export function Test(arg1:kuddle.Session):Promise<boolean>;

export function Upload(arg1:kuddle.Session,arg2:string,arg3:string,arg4:string,arg5:kuddle.EphemeralSettings):Promise<string>;
